if(EXISTS "/home/helheim/FIT/FIT-IVS2023/black_box_test[1]_tests.cmake")
  include("/home/helheim/FIT/FIT-IVS2023/black_box_test[1]_tests.cmake")
else()
  add_test(black_box_test_NOT_BUILT black_box_test_NOT_BUILT)
endif()
