add_test( EmptyTree.InsertNode /home/helheim/FIT/FIT-IVS2023/black_box_test [==[--gtest_filter=EmptyTree.InsertNode]==] --gtest_also_run_disabled_tests)
set_tests_properties( EmptyTree.InsertNode PROPERTIES WORKING_DIRECTORY /home/helheim/FIT/FIT-IVS2023 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( EmptyTree.DeleteNode /home/helheim/FIT/FIT-IVS2023/black_box_test [==[--gtest_filter=EmptyTree.DeleteNode]==] --gtest_also_run_disabled_tests)
set_tests_properties( EmptyTree.DeleteNode PROPERTIES WORKING_DIRECTORY /home/helheim/FIT/FIT-IVS2023 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( EmptyTree.FindNode /home/helheim/FIT/FIT-IVS2023/black_box_test [==[--gtest_filter=EmptyTree.FindNode]==] --gtest_also_run_disabled_tests)
set_tests_properties( EmptyTree.FindNode PROPERTIES WORKING_DIRECTORY /home/helheim/FIT/FIT-IVS2023 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( NonEmptyTree.InsertNode /home/helheim/FIT/FIT-IVS2023/black_box_test [==[--gtest_filter=NonEmptyTree.InsertNode]==] --gtest_also_run_disabled_tests)
set_tests_properties( NonEmptyTree.InsertNode PROPERTIES WORKING_DIRECTORY /home/helheim/FIT/FIT-IVS2023 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( NonEmptyTree.DeleteNode /home/helheim/FIT/FIT-IVS2023/black_box_test [==[--gtest_filter=NonEmptyTree.DeleteNode]==] --gtest_also_run_disabled_tests)
set_tests_properties( NonEmptyTree.DeleteNode PROPERTIES WORKING_DIRECTORY /home/helheim/FIT/FIT-IVS2023 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( NonEmptyTree.FindNode /home/helheim/FIT/FIT-IVS2023/black_box_test [==[--gtest_filter=NonEmptyTree.FindNode]==] --gtest_also_run_disabled_tests)
set_tests_properties( NonEmptyTree.FindNode PROPERTIES WORKING_DIRECTORY /home/helheim/FIT/FIT-IVS2023 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TreeAxioms.Axiom1 /home/helheim/FIT/FIT-IVS2023/black_box_test [==[--gtest_filter=TreeAxioms.Axiom1]==] --gtest_also_run_disabled_tests)
set_tests_properties( TreeAxioms.Axiom1 PROPERTIES WORKING_DIRECTORY /home/helheim/FIT/FIT-IVS2023 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TreeAxioms.Axiom2 /home/helheim/FIT/FIT-IVS2023/black_box_test [==[--gtest_filter=TreeAxioms.Axiom2]==] --gtest_also_run_disabled_tests)
set_tests_properties( TreeAxioms.Axiom2 PROPERTIES WORKING_DIRECTORY /home/helheim/FIT/FIT-IVS2023 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TreeAxioms.Axiom3 /home/helheim/FIT/FIT-IVS2023/black_box_test [==[--gtest_filter=TreeAxioms.Axiom3]==] --gtest_also_run_disabled_tests)
set_tests_properties( TreeAxioms.Axiom3 PROPERTIES WORKING_DIRECTORY /home/helheim/FIT/FIT-IVS2023 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( black_box_test_TESTS EmptyTree.InsertNode EmptyTree.DeleteNode EmptyTree.FindNode NonEmptyTree.InsertNode NonEmptyTree.DeleteNode NonEmptyTree.FindNode TreeAxioms.Axiom1 TreeAxioms.Axiom2 TreeAxioms.Axiom3)
