if(EXISTS "/home/helheim/FIT/FIT-IVS2023/white_box_test[1]_tests.cmake")
  include("/home/helheim/FIT/FIT-IVS2023/white_box_test[1]_tests.cmake")
else()
  add_test(white_box_test_NOT_BUILT white_box_test_NOT_BUILT)
endif()
