add_test( HashMap.Ctor /home/helheim/FIT/FIT-IVS2023/white_box_test [==[--gtest_filter=HashMap.Ctor]==] --gtest_also_run_disabled_tests)
set_tests_properties( HashMap.Ctor PROPERTIES WORKING_DIRECTORY /home/helheim/FIT/FIT-IVS2023 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( HashMap.Reserved /home/helheim/FIT/FIT-IVS2023/white_box_test [==[--gtest_filter=HashMap.Reserved]==] --gtest_also_run_disabled_tests)
set_tests_properties( HashMap.Reserved PROPERTIES WORKING_DIRECTORY /home/helheim/FIT/FIT-IVS2023 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( HashMap.Put /home/helheim/FIT/FIT-IVS2023/white_box_test [==[--gtest_filter=HashMap.Put]==] --gtest_also_run_disabled_tests)
set_tests_properties( HashMap.Put PROPERTIES WORKING_DIRECTORY /home/helheim/FIT/FIT-IVS2023 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( HashMap.Size /home/helheim/FIT/FIT-IVS2023/white_box_test [==[--gtest_filter=HashMap.Size]==] --gtest_also_run_disabled_tests)
set_tests_properties( HashMap.Size PROPERTIES WORKING_DIRECTORY /home/helheim/FIT/FIT-IVS2023 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( HashMap.Capacity /home/helheim/FIT/FIT-IVS2023/white_box_test [==[--gtest_filter=HashMap.Capacity]==] --gtest_also_run_disabled_tests)
set_tests_properties( HashMap.Capacity PROPERTIES WORKING_DIRECTORY /home/helheim/FIT/FIT-IVS2023 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( HashMap.Contains /home/helheim/FIT/FIT-IVS2023/white_box_test [==[--gtest_filter=HashMap.Contains]==] --gtest_also_run_disabled_tests)
set_tests_properties( HashMap.Contains PROPERTIES WORKING_DIRECTORY /home/helheim/FIT/FIT-IVS2023 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( HashMap.Get /home/helheim/FIT/FIT-IVS2023/white_box_test [==[--gtest_filter=HashMap.Get]==] --gtest_also_run_disabled_tests)
set_tests_properties( HashMap.Get PROPERTIES WORKING_DIRECTORY /home/helheim/FIT/FIT-IVS2023 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( HashMap.Pop /home/helheim/FIT/FIT-IVS2023/white_box_test [==[--gtest_filter=HashMap.Pop]==] --gtest_also_run_disabled_tests)
set_tests_properties( HashMap.Pop PROPERTIES WORKING_DIRECTORY /home/helheim/FIT/FIT-IVS2023 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( white_box_test_TESTS HashMap.Ctor HashMap.Reserved HashMap.Put HashMap.Size HashMap.Capacity HashMap.Contains HashMap.Get HashMap.Pop)
